import assert from 'node:assert/strict'
import { remaining, macroTargets, dailySeries, recordedAverage, weightSummary } from '../src/progress.js'
assert.deepEqual(remaining(1500, 1230), { remaining: 270, over: 0 })
assert.deepEqual(remaining(1500, 1600), { remaining: 0, over: 100 })
assert.deepEqual(remaining(1500, 1500), { remaining: 0, over: 0 })
assert.deepEqual(macroTargets(1500), { protein: 75, carbs: 187.5, fat: 50 })
const day = new Date(2026, 8, 8)
const meals = value => ({ 早餐: [{ calories: value }], 午餐: [], 晚餐: [] })
const series = dailySeries([{ mealDate: '2026-09-08', meals: meals(1500) }, { mealDate: '2026-09-06', meals: meals(1000) }, { mealDate: '2026-08-01', meals: meals(9000) }], 7, day)
assert.equal(series[0].date, '2026-09-02')
assert.equal(series[5].value, null)
assert.deepEqual(recordedAverage(series), { count: 2, average: 1250 })
assert.deepEqual(recordedAverage(dailySeries([], 7, day)), { count: 0, average: null })
assert.deepEqual(recordedAverage([{ value: 0 }]), { count: 1, average: 0 })
const weights = [{ date: '2026-09-08', weight: 51.8 }, { date: '2026-08-01', weight: 53 }, { date: '2026-09-06', weight: 52.2 }]
const summary = weightSummary(weights, day)
assert.equal(summary.start.weight, 53)
assert.equal(summary.current.weight, 51.8)
assert.equal(summary.totalChange, -1.2)
assert.equal(summary.weekChange, -0.4)
assert.equal(weightSummary([weights[0]], day).weekChange, null)
assert.equal(weightSummary([], day).totalChange, null)
assert.equal(weightSummary(weights.slice(1), day).weekChange, null)
console.log('PASS: remaining, overage, macro targets, missing days, weekly averages, weight chronology and week boundary')
